# syntax=docker/dockerfile:1

FROM ubuntu

RUN useradd -s /bin/bash -m vscode \
 && groupadd docker \
 && usermod -aG docker vscode
 
RUN wget -qO- https://get.nextflow.io | bash \
 && chmod +x nextflow

USER vscode
